### ISSUE TITLE
String.stringwithBytes() is not a type of String

### ISSUE THREAD

**Issue by clarkathon** [xyyc/SwiftSocket#3]
Do you know of a way to get around the string decoding that will work?  I am seeing everything else just fine.  Just the decoding on the read from my client server is not working.

**Comment by OmarBizreh** [comment]
Dev should update the document I guess, I'm new to swift too, but if you look at the code of his sample on github (here: https://github.com/xyyc/SwiftSocket/blob/master/SwiftSocket/main.swift)
you will see he replaced the String.strignwithBytes() to String(bytes: d, encoding: NSUTF8StringEncoding)
After doing it the error is gone, I haven't yet tested if that is the solution though. Perhaps you could try?

**Comment by xyyc** [comment]
@clarkathon i will update the doc soon.

**Comment by clarkathon** [comment]
@xyyc the code snippet in the socket should actually be:
var data=client.read(1024)
            if let d=data{
                var str = String(bytes: d, encoding: NSUTF8StringEncoding)
                //server_msg = str!
            }

That will put the read data into a string that is useable in this program.
